config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :milestones
  resources :projecs

  resources :sessions

  root to: "users#new"
  resources :users

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base

	has_many :tasks
	belongs_to :projec
end

app/models/projec.rb
class Projec < ActiveRecord::Base
	has_many :milestones
	belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :milestone
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :projecs
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]

  # GET /milestones
  # GET /milestones.json
  def index
    @milestones = Milestone.all
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = Milestone.new(milestone_params)

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to milestones_url, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:name, :description, :start_date, :end_date)
    end
end

app/controllers/projecs_controller.rb
class ProjecsController < ApplicationController
  before_action :set_projec, only: [:show, :edit, :update, :destroy]

  # GET /projecs
  # GET /projecs.json
  def index
    @projecs = Projec.all
  end

  # GET /projecs/1
  # GET /projecs/1.json
  def show
  end

  # GET /projecs/new
  def new
    @projec = Projec.new
  end

  # GET /projecs/1/edit
  def edit
  end

  # POST /projecs
  # POST /projecs.json
  def create
    @projec = Projec.new(projec_params)

    respond_to do |format|
      if @projec.save
        format.html { redirect_to @projec, notice: 'Projec was successfully created.' }
        format.json { render :show, status: :created, location: @projec }
      else
        format.html { render :new }
        format.json { render json: @projec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projecs/1
  # PATCH/PUT /projecs/1.json
  def update
    respond_to do |format|
      if @projec.update(projec_params)
        format.html { redirect_to @projec, notice: 'Projec was successfully updated.' }
        format.json { render :show, status: :ok, location: @projec }
      else
        format.html { render :edit }
        format.json { render json: @projec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projecs/1
  # DELETE /projecs/1.json
  def destroy
    @projec.destroy
    respond_to do |format|
      format.html { redirect_to projecs_url, notice: 'Projec was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projec
      @projec = Projec.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projec_params
      params.require(:projec).permit(:name, :description, :start_date, :end_date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to projecs_path, notice: "Logged In"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url , notice: "Logged Out! "
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :start_date, :end_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projecs_helper.rb
module ProjecsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Project</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	
		<div id="container">
			<div id="user_header">
				<% if current_user %>
					Logged in as <%= current_user.email %>.
					<%= link_to "Log Out" , session_path("current"), method: "delete" %>
				<% else %>
					<%= link_to "Sign Up" , new_user_path %> or
					<%= link_to "Log In" , new_session_path %>
				<% end %>
			</div>

			<% flash.each do |name,msg| %>
				<%= content_tag :div, msg, id: "flash_#{name}" %>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/milestones/_form.html.erb
<%= form_for(@milestone) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing Milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

app/views/milestones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Milestones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @milestones.each do |milestone| %>
      <tr>
        <td><%= milestone.name %></td>
        <td><%= milestone.description %></td>
        <td><%= milestone.start_date %></td>
        <td><%= milestone.end_date %></td>
        <td><%= link_to 'Show', milestone %></td>
        <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
        <td><%= link_to 'Destroy', milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Milestone', new_milestone_path %>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @milestone.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @milestone.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @milestone.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @milestone.end_date %>
</p>

<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>

app/views/projecs/_form.html.erb
<%= form_for(@projec) do |f| %>
  <% if @projec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projec.errors.count, "error") %> prohibited this projec from being saved:</h2>

      <ul>
      <% @projec.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projecs/edit.html.erb
<h1>Editing Projec</h1>

<%= render 'form' %>

<%= link_to 'Show', @projec %> |
<%= link_to 'Back', projecs_path %>

app/views/projecs/index.html.erb
<h1>Listing Projecs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projecs.each do |projec| %>
      <tr>
        <td><%= projec.name %></td>
        <td><%= projec.description %></td>
        <td><%= projec.start_date %></td>
        <td><%= projec.end_date %></td>
        <td><%= link_to 'Show', projec %></td>
        <td><%= link_to 'Edit', edit_projec_path(projec) %></td>
        <td><%= link_to 'Destroy', projec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_projec_path %>

app/views/projecs/new.html.erb
<h1>New Projec</h1>

<%= render 'form' %>

<%= link_to 'Back', projecs_path %>

app/views/projecs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @projec.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @projec.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @projec.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @projec.end_date %>
</p>

<%= link_to 'Edit', edit_projec_path(@projec) %> |
<%= link_to 'Back', projecs_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.text_field :email , :placeholder => "Email" %>
	</div>

	<div class="field">
		<%= f.password_field :password , :placeholder => "Password" %>
	</div>

	<div class="field">
		<%= f.password_field :password_confirmation , :placeholder => "Password Confirmation" %>
	</div>
	<div class="actions">
		<%= f.submit nil, :class => 'btn btn-primary' %>
    	<%= link_to t('.cancel', :default => t("helpers.links.cancel")), new_session_path, :class => 'btn btn-default' %>
    </div>
<% end %>